//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.20 at 10:26:03 AM SAST 
//


package za.co.discovery.assignment.francischinyanaga.spring.soap.api.planetdistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="originPlanet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="distinationPlanet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Route" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "originPlanet",
    "distinationPlanet",
    "route",
    "distance"
})
@XmlRootElement(name = "Acknowledgement")
public class Acknowledgement {

    @XmlElement(required = true)
    protected String originPlanet;
    @XmlElement(required = true)
    protected String distinationPlanet;
    @XmlElement(name = "Route", required = true)
    protected String route;
    protected double distance;

    /**
     * Gets the value of the originPlanet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginPlanet() {
        return originPlanet;
    }

    /**
     * Sets the value of the originPlanet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginPlanet(String value) {
        this.originPlanet = value;
    }

    /**
     * Gets the value of the distinationPlanet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistinationPlanet() {
        return distinationPlanet;
    }

    /**
     * Sets the value of the distinationPlanet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistinationPlanet(String value) {
        this.distinationPlanet = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoute(String value) {
        this.route = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     */
    public double getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     */
    public void setDistance(double value) {
        this.distance = value;
    }

}
