//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.20 at 10:26:03 AM SAST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.discovery.co.za/assignment/francischinyanaga/spring/soap/api/planetDistance", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package za.co.discovery.assignment.francischinyanaga.spring.soap.api.planetdistance;
